### ISSUE TITLE
Failed to execute Docker extractor

### ISSUE THREAD

**Issue by bauerj** [fkie-cad/FACT_core#427] opened 2020-06-10 12:34 UTC
Hey,

shortly after updating a firmware image, this exception occurs:

```
[2020-06-10 14:29:34][unpack_base][ERROR]: Failed to execute docker extractor with code 1:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "./docker_extraction.py", line 40, in <module>
    exit(main())
  File "./docker_extraction.py", line 32, in main
    input_file = list(input_dir.iterdir())[0]
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'

Process Unpacking-Worker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/johann/FACT_core/src/helperFunctions/process.py", line 57, in run
    raise exception
  File "/home/johann/FACT_core/src/helperFunctions/process.py", line 52, in run
    Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/johann/FACT_core/src/scheduler/Unpacking.py", line 69, in unpack_worker
    extracted_objects = unpacker.unpack(fo)
  File "/home/johann/FACT_core/src/unpacker/unpack.py", line 40, in unpack
    extracted_files = self.extract_files_from_file(file_path, tmp_dir.name)
  File "/home/johann/FACT_core/src/unpacker/unpack_base.py", line 29, in extract_files_from_file
    raise RuntimeError(error)
RuntimeError: Failed to execute docker extractor with code 1:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "./docker_extraction.py", line 40, in <module>
    exit(main())
  File "./docker_extraction.py", line 32, in main
    input_file = list(input_dir.iterdir())[0]
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'

[2020-06-10 14:29:38][process][ERROR]: Exception in Unpacking process
[2020-06-10 14:29:38][process][ERROR]: Traceback (most recent call last):
  File "/home/johann/FACT_core/src/helperFunctions/process.py", line 52, in run
    Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/johann/FACT_core/src/scheduler/Unpacking.py", line 69, in unpack_worker
    extracted_objects = unpacker.unpack(fo)
  File "/home/johann/FACT_core/src/unpacker/unpack.py", line 40, in unpack
    extracted_files = self.extract_files_from_file(file_path, tmp_dir.name)
  File "/home/johann/FACT_core/src/unpacker/unpack_base.py", line 29, in extract_files_from_file
    raise RuntimeError(error)
RuntimeError: Failed to execute docker extractor with code 1:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "./docker_extraction.py", line 40, in <module>
    exit(main())
  File "./docker_extraction.py", line 32, in main
    input_file = list(input_dir.iterdir())[0]
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'
[2020-06-10 14:29:38][process][WARNING]: restarting Unpacking 0 process
```

The analysis never finishes and this seems to happen for all firmware images.

FACT is running on a fresh Ubuntu 20.04 installation, I followed the instructions in INSTALL.md. I didn't change anything except for the listening interface:

```
johann@firmware:~/FACT_core$ git describe
2.2-2892-g13f7a92e
johann@firmware:~/FACT_core$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/config/uwsgi_config.ini

no changes added to commit (use "git add" and/or "git commit -a")
johann@firmware:~/FACT_core$ git diff
diff --git a/src/config/uwsgi_config.ini b/src/config/uwsgi_config.ini
index 7f405730..4a047e70 100644
--- a/src/config/uwsgi_config.ini
+++ b/src/config/uwsgi_config.ini
@@ -1,7 +1,7 @@
 [uwsgi]

 # bind to the specified UNIX/TCP socket using HTTP protocol
-http-socket = 127.0.0.1:5000
+http-socket = 0.0.0.0:5000

 # enable the stats server on the specified address
 # (allows you to export uWSGI’s internal statistics as JSON)
@@ -28,4 +28,4 @@ uwsgi_max_temp_file_size = 4096m

 uwsgi_read_timeout = 600

-uwsgi_send_timeout = 600
\ No newline at end of file
+uwsgi_send_timeout = 600
```

Any idea how to solve this?

**Comment by dorpvom** [comment] 2020-06-11 16:14
Hi,
first of all: No. No idea from just looking on the traceback. This problem can't originate from you running Focal nor from the changes, just as you are expecting.
The original issue is the `FileNotFoundError` which happens inside the extractor container. Tomorrow I should be able to post a patch that you can use to produce more debug information on the crash.

I hope that sheds some light on the root cause.

**Comment by bauerj** [comment] 2020-06-13 10:13
Hi Johannes,

it would be great if you could provide that patch.

Thanks and have a nice weekend!

**Comment by dorpvom** [comment] 2020-06-15 12:25
Sooo. First this litlle patch on FACT should give some insights:

```diff
diff --git a/src/unpacker/unpack_base.py b/src/unpacker/unpack_base.py
index eba74f03..b609096a 100644
--- a/src/unpacker/unpack_base.py
+++ b/src/unpacker/unpack_base.py
@@ -20,6 +20,9 @@ class UnpackBase:
         self._initialize_shared_folder(tmp_dir)
         shutil.copy2(file_path, str(Path(tmp_dir, 'input', Path(file_path).name)))
 
+        logging.info('Content of input dir: {}'.format(list(Path(tmp_dir, 'input').iterdir())))
+        logging.info('Stats of input dir: {}'.format(Path(tmp_dir, 'input').stat()))
+
         output, return_code = execute_shell_command_get_return_code(
             'docker run --privileged -m {}m -v /dev:/dev -v {}:/tmp/extractor --rm fkiecad/fact_extractor'.format(self.config.get('unpack', 'memory_limit', fallback='1024'), tmp_dir)
         )
```

That produces something like

```
[2020-06-15 14:22:44][unpack_base][INFO]: Content of input dir: [PosixPath('/tmp/fact_unpack_pox2fsek/input/0c493b682ba8d79ea0ea09c3ca56c60317a1b92c6e15a8a673a5298d5516ce7c_639541')]
[2020-06-15 14:22:44][unpack_base][INFO]: Stats of input dir: os.stat_result(st_mode=16893, st_ino=13898253, st_dev=64768, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1592223764, st_mtime=1592223764, st_ctime=1592223764)
```

and shows if the error is in prepping the extraction directory.

**Comment by dorpvom** [comment] 2020-06-15 12:27
Next thing is to patch the extractor. For that, the extractor has to be built manually though and another little change in FACT is necessary to use the custom container [... coming soon].

**Comment by dorpvom** [comment] 2020-06-15 12:39
So this is the patch for the [extractor](https://github.com/fkie-cad/fact_extractor): 

```diff
diff --git a/fact_extractor/docker_extraction.py b/fact_extractor/docker_extraction.py
index c3c55f7..6155bcc 100755
--- a/fact_extractor/docker_extraction.py
+++ b/fact_extractor/docker_extraction.py
@@ -16,7 +16,7 @@
     You should have received a copy of the GNU General Public License
     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 '''
-
+import logging
 from pathlib import Path
 
 from helperFunctions.config import get_config_dir
@@ -29,9 +29,14 @@ def main():
     setup_logging(debug=False)
 
     input_dir = Path(config.get('unpack', 'data_folder'), 'input')
-    input_file = list(input_dir.iterdir())[0]
-
-    unpack(input_file, config)
+    try:
+        input_file = list(input_dir.iterdir())[0]
+        unpack(input_file, config)
+    except FileNotFoundError as error:
+        logging.error('Content of parent dir: {}'.format(list(input_dir.parent.iterdir())))
+        logging.error('Content of input dir: {}'.format(list(input_dir.iterdir())))
+        logging.error('Stats of input dir: {}'.format(input_dir.stat()))
+        logging.error(error)
 
     return 0
 ```

To apply this to your FACT installation build the extractor container with `docker build -t adapted_extractor .` from the extractor root directory and use this adapted patch on FACT (based on the first one):

```diff
diff --git a/src/unpacker/unpack_base.py b/src/unpacker/unpack_base.py
index eba74f03..bc9cd6e2 100644
--- a/src/unpacker/unpack_base.py
+++ b/src/unpacker/unpack_base.py
@@ -20,8 +20,11 @@ class UnpackBase:
         self._initialize_shared_folder(tmp_dir)
         shutil.copy2(file_path, str(Path(tmp_dir, 'input', Path(file_path).name)))
 
+        logging.info('Content of input dir: {}'.format(list(Path(tmp_dir, 'input').iterdir())))
+        logging.info('Stats of input dir: {}'.format(Path(tmp_dir, 'input').stat()))
+
         output, return_code = execute_shell_command_get_return_code(
-            'docker run --privileged -m {}m -v /dev:/dev -v {}:/tmp/extractor --rm fkiecad/fact_extractor'.format(self.config.get('unpack', 'memory_limit', fallback='1024'), tmp_dir)
+            'docker run --privileged -m {}m -v /dev:/dev -v {}:/tmp/extractor --rm adapted_extractor'.format(self.config.get('unpack', 'memory_limit', fallback='1024'), tmp_dir)
         )
         if return_code != 0:
             error = 'Failed to execute docker extractor with code {}:\n{}'.format(return_code, output)
```

Now with this we can see if the error occurs before calling the extraction container or if some other thing is off.

**Comment by bauerj** [comment] 2020-06-15 13:34
Thanks for your detailed instructions! This is what happens when I run it:

```
[2020-06-15 15:31:46][Unpacking][INFO]: Queue Length (Analysis/Unpack): 0 / 0
[pid: 61737|app: 0|req: 2/4] 139.30.119.67 () {44 vars in 977 bytes} [Mon Jun 15 15:31:27 2020] POST /upload => generated 8395 bytes in 28783 msecs (HTTP/1.1 200) 2 headers in 81 bytes (14832 switches on core 1)
[2020-06-15 15:31:58][unpack_base][INFO]: Content of input dir: [PosixPath('/tmp/fact_unpack_9zmjkuvk/input/174f0ad680e2eb4ad68a807bd53cb261f5e0c0975d87a68c61dbc5fe3baae016_39428947')]
[2020-06-15 15:31:58][unpack_base][INFO]: Stats of input dir: os.stat_result(st_mode=16893, st_ino=2531525, st_dev=2050, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1592227918, st_mtime=1592227917, st_ctime=1592227917)
[2020-06-15 15:31:59][unpack_base][ERROR]: Failed to execute docker extractor with code 1:
[2020-06-15 13:31:59][docker_extraction][ERROR]: Content of parent dir: []
Traceback (most recent call last):
  File "./docker_extraction.py", line 36, in main
    input_file = list(input_dir.iterdir())[0]
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./docker_extraction.py", line 48, in <module>
    exit(main())
  File "./docker_extraction.py", line 40, in main
    logging.error('Content of input dir: {}'.format(list(input_dir.iterdir())))
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'

Process Unpacking-Worker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/johann/FACT_core/src/helperFunctions/process.py", line 57, in run
    raise exception
  File "/home/johann/FACT_core/src/helperFunctions/process.py", line 52, in run
    Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/johann/FACT_core/src/scheduler/Unpacking.py", line 69, in unpack_worker
    extracted_objects = unpacker.unpack(fo)
  File "/home/johann/FACT_core/src/unpacker/unpack.py", line 39, in unpack
    extracted_files = self.extract_files_from_file(file_path, tmp_dir.name)
  File "/home/johann/FACT_core/src/unpacker/unpack_base.py", line 32, in extract_files_from_file
    raise RuntimeError(error)
RuntimeError: Failed to execute docker extractor with code 1:
[2020-06-15 13:31:59][docker_extraction][ERROR]: Content of parent dir: []
Traceback (most recent call last):
  File "./docker_extraction.py", line 36, in main
    input_file = list(input_dir.iterdir())[0]
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./docker_extraction.py", line 48, in <module>
    exit(main())
  File "./docker_extraction.py", line 40, in main
    logging.error('Content of input dir: {}'.format(list(input_dir.iterdir())))
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'

[2020-06-15 15:32:00][process][ERROR]: Exception in Unpacking process
[2020-06-15 15:32:00][process][ERROR]: Traceback (most recent call last):
  File "/home/johann/FACT_core/src/helperFunctions/process.py", line 52, in run
    Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/johann/FACT_core/src/scheduler/Unpacking.py", line 69, in unpack_worker
    extracted_objects = unpacker.unpack(fo)
  File "/home/johann/FACT_core/src/unpacker/unpack.py", line 39, in unpack
    extracted_files = self.extract_files_from_file(file_path, tmp_dir.name)
  File "/home/johann/FACT_core/src/unpacker/unpack_base.py", line 32, in extract_files_from_file
    raise RuntimeError(error)
RuntimeError: Failed to execute docker extractor with code 1:
[2020-06-15 13:31:59][docker_extraction][ERROR]: Content of parent dir: []
Traceback (most recent call last):
  File "./docker_extraction.py", line 36, in main
    input_file = list(input_dir.iterdir())[0]
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./docker_extraction.py", line 48, in <module>
    exit(main())
  File "./docker_extraction.py", line 40, in main
    logging.error('Content of input dir: {}'.format(list(input_dir.iterdir())))
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'


[2020-06-15 15:32:00][process][WARNING]: restarting Unpacking 0 process
[2020-06-15 15:32:38][Unpacking][INFO]: Queue Length (Analysis/Unpack): 0 / 0
```

**Comment by jstucke** [comment] 2020-06-16 08:00
Hey, it seems like the files are there but don't get mounted into the docker container. Could you try to run this small script to test if the container works correctly?

```bash
#!/usr/bin/env bash
mkdir -p extract/input extract/reports
echo "test 123" > test.txt
zip test.zip test.txt
rm test.txt
mv test.zip extract/input/
docker run --privileged -v /dev:/dev -v $(pwd)/extract:/tmp/extractor --rm fkiecad/fact_extractor
```

**Comment by bauerj** [comment] 2020-06-16 09:03
Well, this is really odd:

```
johann@firmware:/tmp$ ./test.sh
  adding: test.txt (stored 0%)
Traceback (most recent call last):
  File "./docker_extraction.py", line 40, in <module>
    exit(main())
  File "./docker_extraction.py", line 32, in main
    input_file = list(input_dir.iterdir())[0]
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extractor/input'
johann@firmware:/tmp$ cd
johann@firmware:~$ /tmp/test.sh
  adding: test.txt (stored 0%)
[2020-06-16 08:44:26][unpackBase][INFO]: Plug-ins available: ['TPWRN702N', 'adobe', 'ambarella', 'ambarella_romfs', 'arj', 'avm_kernel_image', 'avm_sqfs_fake', 'dahua', 'deb', 'dji_drones', 'dlm', 'dsk', 'dsk_extended', 'generic_carver', 'generic_fs', 'intel_hex', 'jffs2', 'nop', 'patool', 'pjl', 'postscript', 'raw', 'ros', 'sevenz', 'sfx', 'sit', 'squash_fs', 'srec', 'tek', 'tpltool', 'ubi_fs', 'ubi_image', 'uboot', 'uefi', 'untrx', 'update_stream', 'xtek', 'yaffs', 'zlib']
[2020-06-16 08:44:26][unpack][INFO]: 1 files extracted
```
This seems to be an issue that only occurs when mounting /tmp. 

I used this as a workaround:

```
diff --git a/src/unpacker/unpack.py b/src/unpacker/unpack.py
index 862e56da..ab352607 100644
--- a/src/unpacker/unpack.py
+++ b/src/unpacker/unpack.py
@@ -32,7 +32,7 @@ class Unpacker(UnpackBase):
             self._store_unpacking_depth_skip_info(current_fo)
             return []

-        tmp_dir = TemporaryDirectory(prefix='fact_unpack_')
+        tmp_dir = TemporaryDirectory(prefix='fact_unpack_', dir="/home/johann/tmp")

         file_path = self._generate_local_file_path(current_fo)
```

Still, I can't really explain this behaviour. I will try your script on a different machine running Ubuntu 20.04 to check whether it's an issue specific to my server.

**Comment by jstucke** [comment] 2020-06-16 13:28
That's good to hear. We could probably add the option to specify a custom temporary directory path to the config file. Temporary directories are also used in other places in FACT so there could be other problems that are not that obvious.

**Comment by dorpvom** [comment] 2020-06-16 14:08
> 
> 
> That's good to hear. We could probably add the option to specify a custom temporary directory path to the config file. Temporary directories are also used in other places in FACT so there could be other problems that are not that obvious.

I thought about that as well. But I'd be interested what the issue is anyway. We could go as far as detecting problems with the `/tmp` and halt the startup procedure before any errors are triggered.

**Comment by bauerj** [comment] 2020-06-16 14:20
Okay, I have been able to reproduce this issue on a fresh installation on a different machine. However, on a third machine I see the correct behaviour.

On first sight, the different is that the "faulty" machines use the Docker provided as a snap while the machine where everything works correctly is using the packages provided by Docker. Maybe this is a feature and snaps do not have access to the host's tmpfs?

**Comment by dorpvom** [comment] 2020-06-17 10:43
We haven't encountered issues with that as of yet. A quick internet search offers [this](https://www.freecodecamp.org/news/managing-ubuntu-snaps/) post. It states that

> The actual .snap files are kept in the /var/lib/snapd/snaps/ directory. When running, those files will be mounted within the root directory /snap/. Looking over there — in the /snap/core/ subdirectory — you’ll see what looks like a regular Linux file system. It’s actually the virtual file system that’s being used by active snaps.

With this acompannying snippet:

```
ls /snap/core/current
bin   dev  home  lib64  meta  opt   root  sbin  srv  tmp  var
boot  etc  lib   media  mnt   proc  run   snap  sys  usr  writable
```

So if the docker snap uses the `/tmp` from that virtual file system and FACT uses the common `/tmp` you have found the root of your problem.

**Comment by jstucke** [comment] 2020-06-18 07:52
As far as i know, snap applications by default have no access rights outside of their folders and the users `/home` directory (if it is not explicitly granted by the snap rights management). This would explain this behaviour. 

Be that as it may, when #429 gets merged, the temp directory path will be configurable in the config file.

**Comment by rhelmke** [comment] 2021-11-12 08:40
Closing as for now. Feel free to re-open in case the problem persists.

**Closed** 2021-11-12 08:40 UTC
