### ISSUE TITLE
cwe checker docker exit without return

### ISSUE THREAD

**Issue by chenjianquan7** [fkie-cad/FACT_core#1164] opened 2023-11-07 05:21 UTC
### FACT version

4.2dev

### Environment

ubuntu

### Steps to reproduce

![image](https://github.com/fkie-cad/FACT_core/assets/26828709/d47a8dab-897c-4f45-b142-05aca0481b75)
docker run with "container = client.containers.run(image, **kwargs)", but docker ps no process, and process stop 
![image](https://github.com/fkie-cad/FACT_core/assets/26828709/c4196328-72a3-4924-a888-f79128b9b629)
![image](https://github.com/fkie-cad/FACT_core/assets/26828709/e0f8cf9b-0bc6-4808-97e0-4f986d7e3148)

### Expeced Behavior

finish

### Installation logs

<details>
    <summary>install.log</summary>

```
PASTE HERE
```
</details>

### Backend logs

<details>
    <summary>fact_main_backend.log</summary>

```
PASTE HERE
```
</details>

### Frontend logs

<details>
    <summary>fact_main_frontend.log</summary>

```
PASTE HERE
```
</details>

**Comment by jstucke** [comment] 2023-11-07 14:05
duplicate of #1163

**Closed by jstucke** 2023-11-07 14:05 UTC
Labels: bug
