### ISSUE TITLE
Remove Fedora support

### ISSUE THREAD

**Issue by maringuu** [fkie-cad/FACT_core#1197] opened 2024-02-19 07:18 UTC
It is untested and it currently is [broken](https://github.com/fkie-cad/FACT_core/tree/3ae3656821672676d3a1d97018d286dfe237fd60/src/install/pre_install_fedora.sh) anyways.

**Comment by jstucke** [comment] 2024-12-04 09:42
Duplicate of #1072

**Closed by jstucke** 2024-12-04 09:42 UTC
