### ISSUE TITLE
why run many start_fact_backend process 

### ISSUE THREAD

**Issue by chenjianquan7** [fkie-cad/FACT_core#810] opened 2022-06-21 10:13 UTC
it should be one process or many process, system very  solw when unpack firmware, what should i optimize performance?
![image](https://user-images.githubusercontent.com/26828709/174776162-d33ac4c5-c076-456e-be53-43f4936a9d0f.png)

**Comment by jstucke** [comment] 2022-06-27 10:12
FACT makes heavy use of multiprocessing. One or more worker processes are started for each analysis plugin (the number can be configured in `main.cfg`). Unpacking a large firmware with thousands of included files may take quite some time. How large is the firmware that you are trying to unpack? You can also adjust the number of unpacking workers in `main.cfg` (option "threads" in section "unpack"). By default it is set to 4.

**Comment by maringuu** [comment] 2024-02-19 08:14
Closing as this is working as intended.

**Closed by maringuu** 2024-02-19 08:14 UTC
