### ISSUE TITLE
Problem when running docker build

### ISSUE THREAD

**Issue by qy201706** [fkie-cad/FACT_core#913] opened 2022-11-26 03:11 UTC
## error logs

[
![image](https://user-images.githubusercontent.com/39509371/204070264-ce58efce-22f6-417e-95a7-863a48e2cbed.png)
](url)

**How can I fix it?please help me.**

**Comment by qy201706** [comment] 2022-11-26 03:16
my Ubuntu is 20.04 on WSL2, docker has been installed.

**Comment by jstucke** [comment] 2022-11-28 08:40
Hi, FACT support in WSL is still somewhat experimental. The cause of the error seems to be a connection issue. Are you working behind a proxy? What happens if you try to run the failing command directly in the terminal outside of docker. Does it work?

```bash
curl https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Common-Credentials/10k-most-common.txt
```

It could also be a temporary thing. What happens if you try to run the installation again? You can also try to run the installation of the problematic plugin directly by running this from the `src` directory:

```bash
python3 plugins/analysis/users_and_passwords/install.py
```

**Comment by jstucke** [comment] 2024-11-13 14:11
Since there has been no update to this issue for quite a while I will close it. Feel free to reopen it if you have additional questions.

**Closed by jstucke** 2024-11-13 14:11 UTC
