### ISSUE TITLE
large file upload support

### ISSUE THREAD

**Issue by weina2016** [fkie-cad/FACT_core#464] opened 2020-08-04 10:23 UTC
Hi,
    I found it didn't analysis  when I upload a firmware. I got the uid of the firmware ,but I didn't find any analysis running. It seemed like it didn't upload successfully.It didn't show any error message. So I had to restart the FACT.(version 3.1)
    Look forward for your response.

**Comment by dorpvom** [comment] 2020-08-05 08:34
Hi,
the issue is to abstract to debug without additional information. We are currently observing some issues in combination with firefox, stemming from long response times. Can you reproduce the issue? If so, it'd be great to see the frontend log.

**Comment by LyleMi** [comment] 2020-09-01 09:25
Hi, I also encountered this problem, maybe you could reproduce it by upload a very big firmware (maybe more than 1GB). I tested it on my own virtual machine and can reproduce the problem stably.

**Comment by jstucke** [comment] 2020-09-02 09:39
We will evaluate the use of the suggested JavaScript tool for circumventing the current problems with large firmware uploads. It could take some time until we get to work on this, though.

**Comment by jstucke** [comment] 2021-11-05 10:23
It seems this fixed itself when we switched to Flask 2, therefore I will close this issue. If there are still problems, please reopen it.

**Closed by jstucke** 2021-11-05 10:23 UTC
Labels: gui, feature request
